### PR TITLE
Ensure run as root and support non-root remote users

### LINKED ISSUE #4: Non root users
> The tests are failing on images with non-root users, as Juliaup and Julia are installed only for the root user at the moment.

https://github.com/JuliaLang/devcontainer-features/blob/60ffc2ed6038ddadba74be815814ac656fde4e14/src/julia/install.sh#L29

_Originally posted by @eitsupi in https://github.com/JuliaLang/devcontainer-features/issues/3#issuecomment-1371053367_

### PR DESCRIPTION
**Pull request by eitsupi**
Fix #4

### CODE REVIEW

File: src/julia/install.sh [hunk 1]
```diff
@@ -1,10 +1,42 @@
-#!/bin/sh
-set -e
+#!/bin/bash
```
Comment (eitsupi) [inline src/julia/install.sh:1]: By changing from sh to bash, it is no longer possible to run in environments where bash is not installed, but because sh does not support arrays, the USERNAME snippet, which is often used in other Features, could not be used.
